---
name: Lint & Unit Tests for s3gw UI
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  frontend-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout s3gw UI
        uses: actions/checkout@v3

      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: src/frontend/package-lock.json

      - name: Install Dependencies
        working-directory: src/frontend
        run: npm ci

      - name: Run Lint
        working-directory: src/frontend
        run: npm run lint

  frontend-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout s3gw UI
        uses: actions/checkout@v3

      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: src/frontend/package-lock.json

      - name: Install Dependencies
        working-directory: src/frontend
        run: npm ci

      - name: Run Unit Tests
        working-directory: src/frontend
        run: npm run test:ci

  backend-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout s3gw UI
        uses: actions/checkout@v3

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install tox
        run: pip install tox

      - name: Check code format
        working-directory: src
        run: tox -e lint

  backend-types:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout s3gw UI
        uses: actions/checkout@v3

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install tox
        run: pip install tox

      - name: Check types
        working-directory: src
        run: tox -e types

  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout s3gw UI
        uses: actions/checkout@v3

      - name: Setup k3d
        uses: nolar/setup-k3d-k3s@v1
        with:
          skip-creation: true

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install tox
        run: pip install tox

      - name: Run tests
        run: |
          make cluster-start
          make test-ui-backend-with-s3gw
        env:
          BE_IMAGE_TAG: v0.17.0

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
